### ISSUE TITLE
Good job, thank you. Big sur?

### ISSUE THREAD

**Issue by theMonk3y** [chilledHamza/Hackintosh_Legion_Y7000_2018#1] opened 2020-12-26 12:48 UTC
Thank you for your sharing Hamza. Great job. 
Working for big sur ?

**Comment by chilledHamza** [comment] 2020-12-26 14:41
Yes, I have Big Sur 11.0.1 installed currently (didn't update to 11.1 yet, but should work).

**Comment by theMonk3y** [comment] 2020-12-26 17:02
> Yes, I have Big Sur 11.0.1 installed currently (didn't update to 11.1 yet, but should work).

super! i till try it today!

**Comment by theMonk3y** [comment] 2020-12-26 18:04
you have tried itlwm? fix for intel wifi (link below). I do not know if it is stable enough to include in your efi but you can try!

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

**Comment by chilledHamza** [comment] 2020-12-26 18:20
I have Dell DW-1830 installed (supported natively OOB), machine originally had Intel Wireless 3165. I'm aware of OpenIntelWireless project and i'm using it on my other machine (Haier Y11C, Wi-Fi soldered can't replace). i'll say it's stable enough for normal usage (specially after recent TX aggression mira_node patches). You can use it, try AirportItlwm 1.2.0-alpha for Big Sur.

I don't plan to include it in EFI (yet), you can customize it according to your hardware. with Hackintosh one should have understanding of what they are dealing with.

Buttons work, but only when there is a finger present on touchpad, issue here is that Apple Trackpads don't have separate buttons and VoodooI2C emulates Apple Trackpad. Buttons didn't work at all before VoodooI2C version 2.6.0 (haven't tested 2.6.1 yet). Hopefully buttons will be fixed soon.

**Comment by chilledHamza** [comment] 2020-12-26 18:28
numlock can be enabled by modifying VoodooPS2Keyboard init code a little bit, actually i had it enabled before i found the issue and ended up with a fix.

PS. I can try similar fix for Touchpad buttons, but I think VoodooI2C/Acidanthera developers can do it a lot better than my patch

**Comment by theMonk3y** [comment] 2020-12-26 18:31
if you do not try you will not know who will do it better!! 😅
I'm waiting for good news! 🤝

**Comment by theMonk3y** [comment] 2021-01-04 13:21
Hey dude! Any news about touchpad buttons???

**Comment by chilledHamza** [comment] 2021-01-07 11:08
nope, nothing yet

**Closed** 2021-01-13 18:31 UTC

**Comment by chilledHamza** [comment] 2021-03-01 14:44
> any way to do the numlock enable everytime after restart?

[VoodooPS2.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y7000_2018/files/6062308/VoodooPS2.zip) 
In SSDT-NumLock
- set `NumLockSupport -> y` to enable the NumLock key
- set `NumLockOnAtBoot -> y` to set NumLock state to ON at Boot-up

> Hey dude! Any news about touchpad buttons???

[VoodooI2C.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y7000_2018/files/6062309/VoodooI2C.zip)

credit: @usr-sse2 for the fix.

I'll update both in my EFI with next OpenCore Release.

**Comment by theMonk3y** [comment] 2021-03-01 16:50
super!!!!

i have 2 problems. i Reinstall big sur on my y530 with your EFI. 
but this time i have 2 issues:
A. at the boot on opencore the Apples Logo is 5times bigger than normal
B. Touchpad dosent work not at all. if i'm not mistaken we have to do something through the windows to make it work; 

Thank youuuu!

**Comment by chilledHamza** [comment] 2021-03-01 18:04
> A. at the boot on opencore the Apples Logo is 5times bigger than normal

set UIScale to 01 (currently it's 02), you can find it in config.plist under NVRAM -> Add.
I enabled [HiDPI](https://github.com/xzhih/one-key-hidpi) to make text more readable(macOS not OpenCore), that also changed the 2nd stage logo size so, I also changed the stage 1 with UIScale variable.

> B. Touchpad dosent work not at all. if i'm not mistaken we have to do something through the windows to make it work;

Try VoodooI2C from my last comment, it is working fine for me. also make sure `Force unlock on all GPIO pads` is Enabled in BIOS settings. I had Trackpad issue some time ago, VoodooInput was failing to load but everything is fine right now (with latest version that I compiled a few hours ago). 

PS. Don't need Windows, the Windows script just enables `Force unlock on all GPIO pads` in BIOS, as Y530 have Advanced menu available windows is not needed. Y540 and above cannot access advanced BIOS Menu so, script comes handy.

**Comment by theMonk3y** [comment] 2021-03-01 18:07
> > A. at the boot on opencore the Apples Logo is 5times bigger than normal
> 
> set UIScale to 01 (currently it's 02), you can find it in config.plist under NVRAM -> Add.
> I enabled [HiDPI](https://github.com/xzhih/one-key-hidpi) to make text more readable(macOS not OpenCore), that also changed the 2nd stage logo size so, I also changed the stage 1 with UIScale variable.
> 
> > B. Touchpad dosent work not at all. if i'm not mistaken we have to do something through the windows to make it work;
> 
> Try VoodooI2C from my last comment, it is working fine for me. also make sure `Force unlock on all GPIO pads` is Enabled in BIOS settings. I had Trackpad issue some time ago, VoodooInput was failing to load but everything is fine right now (with latest version that I compiled a few hours ago).
> 
> PS. Don't need Windows, the Windows script just enables `Force unlock on all GPIO pads` in BIOS, as Y530 have Advanced menu available windows is not needed. Y540 and above cannot access advanced BIOS Menu so, script comes handy.

ok i will try now and give you know! thank for the fast replay dude!

**Comment by theMonk3y** [comment] 2021-03-01 18:30
> > A. at the boot on opencore the Apples Logo is 5times bigger than normal
> 
> set UIScale to 01 (currently it's 02), you can find it in config.plist under NVRAM -> Add.
> I enabled [HiDPI](https://github.com/xzhih/one-key-hidpi) to make text more readable(macOS not OpenCore), that also changed the 2nd stage logo size so, I also changed the stage 1 with UIScale variable.
> 
> > B. Touchpad dosent work not at all. if i'm not mistaken we have to do something through the windows to make it work;
> 
> Try VoodooI2C from my last comment, it is working fine for me. also make sure `Force unlock on all GPIO pads` is Enabled in BIOS settings. I had Trackpad issue some time ago, VoodooInput was failing to load but everything is fine right now (with latest version that I compiled a few hours ago).
> 
> PS. Don't need Windows, the Windows script just enables `Force unlock on all GPIO pads` in BIOS, as Y530 have Advanced menu available windows is not needed. Y540 and above cannot access advanced BIOS Menu so, script comes handy.

enable this = Force unlock on all GPIO pads fix the problem! 

touchpad buttons still not working with 
"VoodooI2C.zip
credit: @usr-sse2 for the fix.."

unfortunately !!

**Comment by chilledHamza** [comment] 2021-03-01 18:51
> unfortunately !! maybe i need to do some extra corrections in plist? y530 my laptop!

Disable `Force click and haptic feedback` under Trackpad Preferance pane.

<img width="780" alt="Screen Shot 2021-03-01 at 11 42 49 PM" src="https://user-images.githubusercontent.com/32929979/109544084-f10b8f00-7ae8-11eb-8fe3-fe3806943bad.png">

**Comment by theMonk3y** [comment] 2021-03-01 18:54
> > unfortunately !! maybe i need to do some extra corrections in plist? y530 my laptop!
> 
> Disable `Force click and haptic feedback` under Trackpad Preferance pane.
> 
> <img alt="Screen Shot 2021-03-01 at 11 42 49 PM" width="780" src="https://user-images.githubusercontent.com/32929979/109544084-f10b8f00-7ae8-11eb-8fe3-fe3806943bad.png">

you are a small god!!!!!! Thank youuuu!! @chilledHamza @usr-sse2

**Comment by usr-sse2** [comment] 2021-03-01 18:55
> > unfortunately !! maybe i need to do some extra corrections in plist? y530 my laptop!
> 
> 
> 
> Disable `Force click and haptic feedback` under Trackpad Preferance pane.
> 
> 
> 
> <img width="780" alt="Screen Shot 2021-03-01 at 11 42 49 PM" src="https://user-images.githubusercontent.com/32929979/109544084-f10b8f00-7ae8-11eb-8fe3-fe3806943bad.png">
> 
> 

and reboot - somewhy it doesn't update the setting until reboot

**Comment by theMonk3y** [comment] 2021-03-01 18:57
> > > unfortunately !! maybe i need to do some extra corrections in plist? y530 my laptop!
> > 
> > 
> > Disable `Force click and haptic feedback` under Trackpad Preferance pane.
> > <img alt="Screen Shot 2021-03-01 at 11 42 49 PM" width="780" src="https://user-images.githubusercontent.com/32929979/109544084-f10b8f00-7ae8-11eb-8fe3-fe3806943bad.png">
> 
> and reboot - somewhy it doesn't update the setting until reboot

its working without reboot!! im so fuc%# happy 🥇

**Comment by chilledHamza** [comment] 2021-03-05 22:22
@usr-sse2 Earlier I tested this on a Lenovo Rescuer Y7000 (chinese variant of Legion Y530) : Synaptics (SYNA2B46) and it worked perfectly. @theMonk3y also reported success, I guess he also have SYNA2B46.

Now I tested it on a Lenovo Legion Y530, this one have a ELAN061B Trackpad. Issue is that only Left Button is working (but does the job of Right Button instead). Right Button isn't doing anything. Can't click/select anything, so at least both are not swapped (I guess).

PS: just noticed Right is detected, but not the way it's supposed to. for example if I press it at some specific line in this comment box, cursor is moved to that line (or place in text). but I cannot click/select/drag folder or files with it.

**Comment by theMonk3y** [comment] 2021-03-14 10:32
@chilledHamza goodmorning, dude sorry for offtopic. maybe you can help me with my L340 ? i try a week to configure it but no luck! laptops is really hard.

**Comment by chilledHamza** [comment] 2021-03-14 12:29
@theMonk3y What's the issue you are having?

**Comment by theMonk3y** [comment] 2021-03-14 12:33
> @theMonk3y What's the issue you are having?

thank you for answer dude!
i installed big sur latest, build opencore, everythink looks great only the VIDEO dosent work. 
"graphics display 8mb". 
(Lenovo Ideapad L340-15IRH Gaming (i5-9300H/8GB/256GB/GeForce GTX 1050)
EFI = https://mega.nz/file/wkQ32A7I#tEW3HukgvjbrYh_bnmyJJTjRAZ9jHBvyYoKk6xCGXjY

**Comment by chilledHamza** [comment] 2021-03-14 12:58
> "graphics display 8mb".

Try to boot with this config.plist, this worked on i5-9300H (Pavilion-15 DK0056WM, a friend have it)
[config.zip](https://github.com/chilledHamza/Hackintosh_Legion_Y7000_2018/files/6136693/config.zip)


> i think i need to disable nvidia and start the intel graphics but i dont know how to do that....

Add [SSDT-NoHybGfx.aml](https://github.com/chilledHamza/Hackintosh_Legion_Y7000_2018/blob/main/EFI/OC/ACPI/SSDT-NoHybGfx.aml) to ACPI folder and also add it to config.plist (under ACPI -> Add). This method is for Lenovo specifically, you might have to edit it a little bit according to your Nvidia GPU declaration in ACPI (BIOS Device Name). 
Details at [Dortania : Disabling laptop dGPUs](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html)

Also you don't have to disable Nvidia to make iGPU work, Nvidia is disabled because we don't have Optimus drivers to make it work on macOS. so it's disabled to save power, lower device temperature and increase battery life.

**Comment by theMonk3y** [comment] 2021-03-14 13:05
> Edit : you already have "-wegnoegpu" in boot-args, that is enough to hide Nvidia GPU from macOS. it's basic method to avoid issues, but ACPI approach is prefered for better results. "-wegnoegpu" only hide it (won't turn it off), dGPU will still drain battery and laptop will run hot without any load.

with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal.

**Comment by chilledHamza** [comment] 2021-03-14 13:15
> with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.

[Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)

**Comment by theMonk3y** [comment] 2021-03-14 14:55
> > with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.
> 
> [Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)

no luck! i do something wrong i think.

**Comment by chilledHamza** [comment] 2021-03-14 18:21
> > > with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.
> > 
> > 
> > [Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)
> 
> no luck! i do something wrong i think.

I changed the ig-platform-id, that can be the cause of gIOScreenLockState. revert it back to original (EFI you attached) or try some alternative ig-platform-id

**Comment by theMonk3y** [comment] 2021-03-16 10:37
> > > > with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.
> > > 
> > > 
> > > [Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)
> > 
> > 
> > no luck! i do something wrong i think.
> 
> I changed the ig-platform-id, that can be the cause of gIOScreenLockState. revert it back to original (EFI you attached) or try some alternative ig-platform-id

dude........i cant believe this... this cpu coming without UHD Graphics!! cmon intel! (i9300HF) i spend 3 days to find this problem! lol

**Comment by chilledHamza** [comment] 2021-03-20 12:46
> > > > > with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.
> > > > 
> > > > 
> > > > [Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)
> > > 
> > > 
> > > no luck! i do something wrong i think.
> > 
> > 
> > I changed the ig-platform-id, that can be the cause of gIOScreenLockState. revert it back to original (EFI you attached) or try some alternative ig-platform-id
> 
> dude........i cant believe this... this cpu coming without UHD Graphics!! cmon intel! (i9300HF) i spend 3 days to find this problem! lol back to the windows for this laptop!

I saw some desktop version of these chips (9400F & 10400F) never though that there was also a Mobile version as well. That leaves the Nvidia GPU only, if it's Pascal or older (highly unlikely) then you can install High Sierra + Web-Drivers to get GPU acceleration. For Turing and newer GPUs there are no Web-Drivers so better stick with Windows/Linux.

**Comment by theMonk3y** [comment] 2021-03-20 18:04
> > > > > > with -wegnoegpu in boot args is freeze on boot, i delete it now to boot normal. Freeze on all done going home.
> > > > > 
> > > > > 
> > > > > [Stuck on or near IOConsoleUsers: gIOScreenLock.../gIOLockState (3...](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-or-near-ioconsoleusers-gioscreenlock-giolockstate-3)
> > > > 
> > > > 
> > > > no luck! i do something wrong i think.
> > > 
> > > 
> > > I changed the ig-platform-id, that can be the cause of gIOScreenLockState. revert it back to original (EFI you attached) or try some alternative ig-platform-id
> > 
> > 
> > dude........i cant believe this... this cpu coming without UHD Graphics!! cmon intel! (i9300HF) i spend 3 days to find this problem! lol back to the windows for this laptop!
> 
> I saw some desktop version of these chips (9400F & 10400F) never though that there was also a Mobile version as well. That leaves the Nvidia GPU only, if it's Pascal or older (highly unlikely) then you can install High Sierra + Web-Drivers to get GPU acceleration. For Turing and newer GPUs there are no Web-Drivers so better stick with Windows/Linux.

i try High Sierra but no, Its really old now! better to stay on windows 10 for this laptop!

**Comment by theMonk3y** [comment] 2021-05-07 06:55
Hello Hamza!! Any update for Y530??
thank you buddy!

**Comment by chilledHamza** [comment] 2021-05-07 13:09
@theMonk3y so far everything is working fine. Except trackpad button on ELAN061B, but i believe you have the SYNA2B46 trackpad (button work fine for you).

Updated OpenCore and Kexts, but didn't push to main branch. I'll update the repo sometime soon, but changes doesn't really matter if everything is working fine.

**Comment by theMonk3y** [comment] 2021-05-07 15:45
> @theMonk3y so far everything is working fine. Except trackpad button on ELAN061B, but i believe you have the SYNA2B46 trackpad (button work fine for you).
> 
> Updated OpenCore and Kexts, but didn't push to main branch. I'll update the repo sometime soon, but changes doesn't really matter if everything is working fine.

yeah everything work super. can I update with this open core to the latest Big Sur???

**Comment by chilledHamza** [comment] 2021-05-07 16:44
> yeah everything work super. can I update with this open core to the latest Big Sur???

I have 11.2.3 installed currently (didn't update to 11.3.1 yet). but 11.3.1 should work fine as well.

**Comment by theMonk3y** [comment] 2021-05-10 16:12
> > yeah everything work super. can I update with this open core to the latest Big Sur???
> 
> I have 11.2.2 installed currently (didn't update to 11.3.1 yet). but 11.3.1 should work fine as well.

thank you for fast update dude!!

everything works perfect. 
check the itlwm again! with the latest update its working super.

**Comment by chilledHamza** [comment] 2021-05-10 16:45
> check the itlwm again! with the latest update its working super.

I'm aware of Itlwm project, personally using Alpha 2.0.0 on my other laptop (Soldered Wi-Fi/BT module, not user replaceable).

But i did install a supported Broadcom module (DW-1830) in Y530, so i didn't include AirportItlwm. if you have Intel Wi-Fi you can use kernel extensions from [OpenIntelWireless](https://github.com/OpenIntelWireless)

**Comment by theMonk3y** [comment] 2021-07-20 13:30
Hello buddy! any update for our machine?? (open core)
thank youuu!

**Comment by chilledHamza** [comment] 2021-07-24 23:18
> Hello buddy! 

Hi mate, saw your message and forgot to reply.. sorry about that.

> any update for our machine?? (open core)

Everything is working fine so far, no major issues and should be able to run latest Big Sur v11.5 (feel free to report any bugs you encounter)

Monterey Beta release will require modifications. I'm aware of Bluetooth changes, everything else is fine only Bluetooth Firmware loading mechanism is changed (there might be other changes with future beta releases)

Personally I'm not into Beta releases anymore, so I'll wait for final release.

**Comment by theMonk3y** [comment] 2021-07-26 04:52
> > Hello buddy!
> 
> Hi mate, saw your message and forgot to reply.. sorry about that.
> 
> > any update for our machine?? (open core)
> 
> Everything is working fine so far, no major issues and should be able to run latest Big Sur v11.5 (feel free to report any bugs you encounter)
> 
> Monterey Beta release will require modifications. I'm aware of Bluetooth changes, everything else is fine only Bluetooth Firmware loading mechanism is changed (there might be other changes with future beta releases)
> 
> Personally I'm not into Beta releases anymore, so I'll wait for final release.

super! lets wait the release! thank you for your job dude! have a good week!
